### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by jay-thakur** [autonomousvision/differentiable_volumetric_rendering#15]
Hi,

I am trying to run this on Windows CPU Machine.

Executed `python generate.py configs/demo/demo_combined.yaml` but getting below error - 

```
=> Loading checkpoint from url...
  0%|                                                                                                                                                | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "generate.py", line 207, in <module>
    main()  # execute this only when run directly, not when imported!
  File "generate.py", line 128, in main
    out = generator.generate_mesh(data)
  File "C:\Users\jay\differentiable_volumetric_rendering\im2mesh\dvr\generation.py", line 70, in generate_mesh
    mesh = self.generate_from_latent(c, stats_dict=stats_dict,
  File "C:\Users\jay\differentiable_volumetric_rendering\im2mesh\dvr\generation.py", line 145, in generate_from_latent
    points = mesh_extractor.query()
  File "im2mesh\utils\libmise\mise.pyx", line 122, in im2mesh.utils.libmise.mise.MISE.query
    cdef long[:, :] points_view = points_np
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
```
I tried changing 
```
points_np = np.zeros((points.size(), 3), dtype=np.int64)
```
to 
```
points_np = np.zeros((points.size(), 3), dtype=np.int32)
```
and 
```
points_np = np.zeros((points.size(), 3), dtype=np.int32_t)
```
But no luck.

Could you please help me.

**Comment by m-niemeyer** [comment]
Hi @jay-thakur , thanks a lot for your interest in our project!

I am sorry but we only tested the code on Linux GPU machines. I do not have access to Windows machines, so I sadly I cannot help you here. Good luck!
